name: Deploy Frontend

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::048916985380:role/GitHubActionsDeployRole
        aws-region: us-east-1

    - name: Install Dependencies
      run: |
        npm install

    - name: Build
      env:
        VUE_APP_API_URL: ${{ secrets.VUE_APP_API_URL }}
      run: |
        npm run build

    - name: Deploy to S3
      run: |
        aws s3 sync dist/ s3://motorcycle-shop-frontend --delete

    - name: Invalidate CloudFront
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
